#+title: Org Literate Config
#+author: Piotr Kozicki
#+property: header-args :tangle yes
#+startup: overview

* Emacs Initialisation
** Settings

Defining sane settings related to global emacs and startup. If in doubt of where to put something,
consider here. Make sure that everything here will always work, or at least produce the minimum needed
to fix something else that might break later in this file.

*** Appearance

Excluding theme, which is installed with ~use-package~ later.

Load font

#+begin_src elisp
  (add-to-list 'default-frame-alist
	       '(font . "JetbrainsMono Nerd Font-13"))
#+end_src

Line numbers

#+begin_src elisp
  (setq display-line-numbers-type 'relative)
  (global-display-line-numbers-mode)
#+end_src

Disable decorations etc.

#+begin_src elisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+end_src

*** Autopairs (electric)

Globally enable the minor ~electric-pair-mode~

#+begin_src elisp
  (electric-pair-mode 1)
#+end_src

This may not provide the best pairs for /every/ programming language. [[https://www.emacswiki.org/emacs/ElectricPair][Add a hook]] as demonstrated in the
documentation, for the specific programming language.

*** Backups

By default, emacs will leave ~file~\~ all over the place - these files are
backups in the case of a crash or similar. Even if this is useful, it's
annoying. I would like to put them all in one place.

#+begin_src elisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
#+end_src

*** Startup screen

#+begin_src elisp
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message nil)
#+end_src

*** Notifications

Turn off that loud beep

#+begin_src elisp
  (setq ring-bell-function 'ignore)
#+end_src

** Package Management

Want to use the use-package macro to make package management easy

#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
#+end_src

* Packages
** Benchmark

See where emacs is taking the longest to load, investigate.

#+begin_src elisp
  (use-package benchmark-init
    :ensure t
    :config
    ;; To disable collection of benchmark data after init is done.
    (add-hook 'after-init-hook 'benchmark-init/deactivate))
#+end_src

** Display

Load gruvbox theme

#+begin_src elisp
  (use-package gruvbox-theme
    :ensure t
    :config
    (load-theme 'gruvbox-dark-hard t))
#+end_src

** Which-key

#+begin_src elisp
  (use-package which-key
    :ensure t
    :config
    (which-key-mode))
#+end_src

** Evil

Vim navigation. ~evil-want-keybinding~ is set to ~nil~ for ~evil-collection~

#+begin_src elisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil
	  evil-want-C-u-scroll t)
    :config
    (evil-mode 1))
#+end_src

*** evil-collection

Improved vim navigation in most contexts

#+begin_src elisp
  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (evil-collection-init))
#+end_src

*** evil-commentary

Comment stuff out quickly

#+begin_src elisp
  (use-package evil-commentary
    :ensure t
    :after evil
    :config
    (evil-commentary-mode))
#+end_src

** Rainbow Delimiters

Colourful delimiters make it easier to tell where they start and stop.

#+begin_src elisp
  (use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src

** Counsel/Ivy

#+begin_src elisp
  (use-package counsel
    :ensure t
    :diminish
    :bind (("C-s" . swiper)
	   ("M-x" . counsel-M-x)
	   :map ivy-minibuffer-map
	   ("TAB" . ivy-alt-done)
	   ("C-l" . ivy-alt-done)
	   ("C-j" . ivy-next-line)
	   ("C-k" . ivy-previous-line)
	   :map ivy-switch-buffer-map
	   ("C-l" . ivy-done)
	   ("C-j" . ivy-next-line)
	   ("C-k" . ivy-previous-line))
    :config
    (ivy-mode 1))
#+end_src

** TODO Org (maths opt.)
** TODO PDF (pdf-tools)
** Projectile

Jump between and easily manage projects and files therein

#+begin_src elisp
  (use-package projectile
    :ensure t
    :config
    (projectile-mode 1)
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))
#+end_src

** Git

View diff in gutter

#+begin_src elisp
  (use-package git-gutter
    :ensure t
    :config
    (global-git-gutter-mode +1))
#+end_src

Interact with git using magit

#+begin_src elisp
  (use-package magit
    :commands (magit magit-diff)
    :ensure t)
#+end_src

** TODO LSP (lsp-mode)
** TODO YASnippet
** General Keybindings

We should be able to use general.el to use leader keys, similar as to vim or spacemacs.

#+begin_src elisp
  (use-package general
    :ensure t
    :config
    (general-create-definer otg/leader-keys
      :keymaps '(normal insert visual)
      :prefix "SPC"
      :global-prefix "C-SPC"))
#+end_src

Note that these keybindings are not comprehensive, separating them as such should keep them easy to change

*** File Operations

#+begin_src elisp
  (otg/leader-keys
       "f" '(:ignore f :which-key "files")
       "ff" '(counsel-find-file :which-key "file find")
       "fs" '(save-buffer :which-key "file save"))
#+end_src

*** Buffer Operations

#+begin_src elisp
  (otg/leader-keys
    "b" '(:ignore b :which-key "buffer")
    "bb" '(counsel-switch-buffer :which-key "buffer switch")
    "bd" '(evil-delete-buffer :which "buffer delete"))
#+end_src

*** Window Operations

#+begin_src elisp
  (otg/leader-keys
    "w" '(:ignore w :which-key "windows")
    "wh" '(evil-window-left :which-key "window right")
    "wj" '(evil-window-down :which-key "window down")
    "wk" '(evil-window-up :which-key "window up")
    "wl" '(evil-window-right :which-key "window right")
    "wH" '(evil-window-move-far-left :which-key "move window left")
    "wJ" '(evil-window-move-very-bottom :which-key "move window down")
    "wK" '(evil-window-move-very-top :which-key "move window up")
    "wL" '(evil-window-move-far-right :which-key "move window right")
    "ws" '(evil-window-split :which-key "horizontal split")
    "wv" '(evil-window-vsplit :which-key "vertical split")
    "wd" '(evil-window-delete :which-key "window delete")
    "wo" '(delete-other-windows :which-key "window only"))
#+end_src

*** Git Operations

#+begin_src elisp
  (otg/leader-keys
    "g" '(:ignore g :which-key "git")
    "gg" '(magit :which-key "git status"))
#+end_src

*** Misc

Commonly accessed keybindings with no particular group or otherwise one-offs

#+begin_src elisp
  (otg/leader-keys
    "s" '(counsel-grep-or-swiper :which-key "search")
    "SPC" '(counsel-M-x :which-key "M-x")
    "qq" '(save-buffers-kill-terminal :which-key "quit"))
#+end_src

* TODO Programming Languages
** C/C++
** Python
** Haskell
